from __future__ import annotations

import hashlib

from src.models.classification import (
    Confidence,
    MultiAgentReview,
    Significance,
)
from src.models.state import EscalationPrecedent, ProcessingState

ESCALATION_CRITERIA = {
    "security_implication",
    "cross_team_impact",
    "irreversible_decision",
    "unresolvable_ambiguity",
    "agent_disagreement",
}


def compute_pattern_hash(review: MultiAgentReview) -> str:
    if not review.perspectives:
        return ""
    # Use all perspectives' change types and files for a robust hash
    parts: list[str] = []
    for p in review.perspectives:
        cls = p.classification
        files_key = ":".join(sorted(cls.relevant_files))
        parts.append(f"{p.perspective}={cls.change_type}:{files_key}")
    key = "|".join(sorted(parts))
    return hashlib.sha256(key.encode()).hexdigest()[:16]


def check_precedent(
    review: MultiAgentReview, state: ProcessingState
) -> EscalationPrecedent | None:
    pattern_hash = compute_pattern_hash(review)
    if not pattern_hash:
        return None
    for precedent in state.escalation_precedents:
        if precedent.pattern_hash == pattern_hash:
            return precedent
    return None


def evaluate_escalation(
    review: MultiAgentReview,
    state: ProcessingState,
) -> MultiAgentReview:
    precedent = check_precedent(review, state)
    if precedent:
        review.escalation_triggered = False
        review.escalation_reason = None
        review.consensus = True
        review.consensus_significance = Significance(precedent.human_decision)
        return review

    criteria_matched: list[str] = []

    if not review.consensus:
        criteria_matched.append("agent_disagreement")

    for p in review.perspectives:
        cls = p.classification
        if cls.change_type.value == "security":
            criteria_matched.append("security_implication")
        if cls.confidence == Confidence.BORDERLINE and cls.significance in (
            Significance.MODERATE,
            Significance.HIGH,
        ):
            criteria_matched.append("unresolvable_ambiguity")

    if criteria_matched:
        review.escalation_triggered = True
        review.escalation_reason = (
            f"Criteria matched: {', '.join(sorted(set(criteria_matched)))}"
        )
    else:
        review.escalation_triggered = False

    return review


def format_escalation_comment(review: MultiAgentReview) -> str:
    lines = [
        "## Architecture Review — Escalation Required",
        "",
        f"**Reason**: {review.escalation_reason}",
        "",
        "### Agent Assessments:",
        "",
    ]

    for p in review.perspectives:
        cls = p.classification
        lines.append(
            f"- **{p.perspective}**: {cls.significance.value} "
            f"(confidence: {cls.confidence.value}) — {cls.rationale}"
        )

    lines.extend(
        [
            "",
            "### Action Required:",
            "Please review the assessments above and resolve this escalation by commenting "
            "with your decision (e.g., `high`, `moderate`, or `non_significant`).",
            "",
            "_This comment was generated by the ADR Review Agent._",
        ]
    )

    return "\n".join(lines)
